const items = [
  {
    id: 1,
    name: 'Elmas',
    emoji: '💎',
    description: 'Değerli ve nadir bir taş.',
    value: 500,
  },
  {
    id: 2,
    name: 'Altın',
    emoji: '🥇',
    description: 'Parlak ve değerli bir metal.',
    value: 300,
  },
  {
    id: 3,
    name: 'Demir',
    emoji: '⛓️',
    description: 'Güçlü ve dayanıklı bir metal.',
    value: 150,
  },
  {
    id: 4,
    name: 'Ahşap',
    emoji: '🪵',
    description: 'Temel yapı malzemesi.',
    value: 50,
  },
  {
    id: 5,
    name: 'Taş',
    emoji: '🪨',
    description: 'Basit maden kayası.',
    value: 30,
  },
  {
    id: 6,
    name: 'Su Şişesi',
    emoji: '💧',
    description: 'Susuzluğu giderir.',
    value: 20,
  },
  {
    id: 7,
    name: 'Yemek Tabağı',
    emoji: '🍽️',
    description: 'Açlığı giderir.',
    value: 40,
  },
  {
    id: 8,
    name: 'Ekmeğimsi',
    emoji: '🍞',
    description: 'Karbonhidrat kaynağı.',
    value: 25,
  },
  { id: 9, name: 'Et', emoji: '🍖', description: 'Protein deposu.', value: 60 },
  {
    id: 10,
    name: 'Balık',
    emoji: '🐟',
    description: 'Denizden gelen lezzet.',
    value: 70,
  },
  {
    id: 11,
    name: 'Elma',
    emoji: '🍎',
    description: 'Sağlıklı bir atıştırmalık.',
    value: 15,
  },
  {
    id: 12,
    name: 'Muz',
    emoji: '🍌',
    description: 'Enerji verici meyve.',
    value: 18,
  },
  {
    id: 13,
    name: 'Üzüm',
    emoji: '🍇',
    description: 'Tatlı ve sulu meyve.',
    value: 22,
  },
  {
    id: 14,
    name: 'Portakal',
    emoji: '🍊',
    description: 'C vitamini kaynağı.',
    value: 20,
  },
  {
    id: 15,
    name: 'Şarap',
    emoji: '🍷',
    description: 'Olgunlaşmış meyve içkisi.',
    value: 150,
  },
  {
    id: 16,
    name: 'Bira',
    emoji: '🍺',
    description: 'Fermente içecek.',
    value: 80,
  },
  {
    id: 17,
    name: 'Kahve',
    emoji: '☕',
    description: 'Güne enerjiyle başla.',
    value: 45,
  },
  {
    id: 18,
    name: 'Çay',
    emoji: '🍵',
    description: 'Rahatlatıcı içecek.',
    value: 30,
  },
  {
    id: 19,
    name: 'Kitap',
    emoji: '📚',
    description: 'Bilgi kaynağı.',
    value: 200,
  },
  {
    id: 20,
    name: 'Harita',
    emoji: '🗺️',
    description: 'Keşif rehberi.',
    value: 120,
  },
  {
    id: 21,
    name: 'Pusula',
    emoji: '🧭',
    description: 'Yön gösterir.',
    value: 110,
  },
  {
    id: 22,
    name: 'Fener',
    emoji: '🔦',
    description: 'Karanlıkta ışık sağlar.',
    value: 90,
  },
  {
    id: 23,
    name: 'Kılıç',
    emoji: '⚔️',
    description: 'Saldırı silahı.',
    value: 300,
  },
  {
    id: 24,
    name: 'Kalkan',
    emoji: '🛡️',
    description: 'Savunma ekipmanı.',
    value: 250,
  },
  {
    id: 25,
    name: 'Ok',
    emoji: '🏹',
    description: 'Uzak saldırı silahı.',
    value: 100,
  },
  {
    id: 26,
    name: 'Yay',
    emoji: '🏹',
    description: 'Ok atmak için.',
    value: 180,
  },
  {
    id: 27,
    name: 'Zırh',
    emoji: '🥋',
    description: 'Koruyucu kıyafet.',
    value: 350,
  },
  {
    id: 28,
    name: 'Cüppe',
    emoji: '🧙‍♂️',
    description: 'Büyücü kıyafeti.',
    value: 220,
  },
  {
    id: 29,
    name: 'Büyü Kitabı',
    emoji: '📖',
    description: 'Gizli sihirler.',
    value: 400,
  },
  {
    id: 30,
    name: 'Mantar',
    emoji: '🍄',
    description: 'Ormanda bulunur.',
    value: 35,
  },
  {
    id: 31,
    name: 'Çiçek',
    emoji: '🌸',
    description: 'Güzel kokulu bitki.',
    value: 25,
  },
  {
    id: 32,
    name: 'Bal',
    emoji: '🍯',
    description: 'Tatlı ve yapışkan.',
    value: 60,
  },
  {
    id: 33,
    name: 'Süt',
    emoji: '🥛',
    description: 'Kalsiyum kaynağı.',
    value: 30,
  },
  {
    id: 34,
    name: 'Yumurta',
    emoji: '🥚',
    description: 'Protein deposu.',
    value: 20,
  },
  {
    id: 35,
    name: 'Makas',
    emoji: '✂️',
    description: 'Kesici alet.',
    value: 50,
  },
  {
    id: 36,
    name: 'Çekiç',
    emoji: '🔨',
    description: 'Çivi çakmak için.',
    value: 70,
  },
  {
    id: 37,
    name: 'Pense',
    emoji: '🔧',
    description: 'Cıvata sıkmak için.',
    value: 65,
  },
  {
    id: 38,
    name: 'Vida',
    emoji: '🔩',
    description: 'Bağlantı parçası.',
    value: 15,
  },
  {
    id: 39,
    name: 'Somun',
    emoji: '🔩',
    description: 'Vida karşıt parça.',
    value: 15,
  },
  {
    id: 40,
    name: 'Matkap',
    emoji: '🛠️',
    description: 'Delme aleti.',
    value: 200,
  },
  {
    id: 41,
    name: 'Testere',
    emoji: '🪚',
    description: 'Kesme aleti.',
    value: 180,
  },
  {
    id: 42,
    name: 'Çekiç',
    emoji: '🔨',
    description: 'Çivi çakmak için.',
    value: 70,
  },
  {
    id: 43,
    name: 'Kredi Kartı',
    emoji: '💳',
    description: 'Dijital para aracı.',
    value: 500,
  },
  {
    id: 44,
    name: 'Anahtar',
    emoji: '🔑',
    description: 'Kilidi açar.',
    value: 80,
  },
  {
    id: 45,
    name: 'Gözlük',
    emoji: '👓',
    description: 'Görmeyi sağlar.',
    value: 150,
  },
  {
    id: 46,
    name: 'Saat',
    emoji: '⌚',
    description: 'Zamanı gösterir.',
    value: 220,
  },
  {
    id: 47,
    name: 'Telefon',
    emoji: '📱',
    description: 'İletişim aracı.',
    value: 800,
  },
  {
    id: 48,
    name: 'Bilgisayar',
    emoji: '💻',
    description: 'Çalışma aracı.',
    value: 1200,
  },
  {
    id: 49,
    name: 'Tablet',
    emoji: '📊',
    description: 'Taşınabilir bilgisayar.',
    value: 900,
  },
  {
    id: 50,
    name: 'Kulaklık',
    emoji: '🎧',
    description: 'Ses dinleme cihazı.',
    value: 300,
  },
  {
    id: 51,
    name: 'Hoparlör',
    emoji: '🔊',
    description: 'Ses çalma cihazı.',
    value: 350,
  },
  {
    id: 52,
    name: 'Mikrofon',
    emoji: '🎤',
    description: 'Ses kaydetme cihazı.',
    value: 250,
  },
  {
    id: 53,
    name: 'Kamera',
    emoji: '📷',
    description: 'Fotoğraf çekme.',
    value: 600,
  },
  {
    id: 54,
    name: 'Film',
    emoji: '🎬',
    description: 'Eğlence kaynağı.',
    value: 100,
  },
  {
    id: 55,
    name: 'Kitaplık',
    emoji: '🪑',
    description: 'Kitaplar için depolama.',
    value: 500,
  },
  {
    id: 56,
    name: 'Masa',
    emoji: '🪞',
    description: 'Çalışma alanı.',
    value: 400,
  },
  {
    id: 57,
    name: 'Sandalye',
    emoji: '🪑',
    description: 'Oturmak için.',
    value: 200,
  },
  {
    id: 58,
    name: 'Koltuk',
    emoji: '🛋️',
    description: 'Rahat oturma.',
    value: 600,
  },
  {
    id: 59,
    name: 'Yorgan',
    emoji: '🛏️',
    description: 'Sıcak tutar.',
    value: 300,
  },
  {
    id: 60,
    name: 'Yastık',
    emoji: '🛏️',
    description: 'Baş desteği.',
    value: 100,
  },
  {
    id: 61,
    name: 'Çarşaf',
    emoji: '🛏️',
    description: 'Yatak örtüsü.',
    value: 150,
  },
  {
    id: 62,
    name: 'Halı',
    emoji: '🧶',
    description: 'Zemin örtüsü.',
    value: 250,
  },
  {
    id: 63,
    name: 'Perde',
    emoji: '🪟',
    description: 'Pencere örtüsü.',
    value: 200,
  },
  {
    id: 64,
    name: 'Lamba',
    emoji: '💡',
    description: 'Işık kaynağı.',
    value: 180,
  },
  { id: 65, name: 'Fan', emoji: '🌀', description: 'Hava akımı.', value: 160 },
  {
    id: 66,
    name: 'Klima',
    emoji: '❄️',
    description: 'Hava soğutma.',
    value: 1000,
  },
  {
    id: 67,
    name: 'Fırın',
    emoji: '🍞',
    description: 'Pişirme aracı.',
    value: 550,
  },
  {
    id: 68,
    name: 'Buzdolabı',
    emoji: '🧊',
    description: 'Yiyecek koruma.',
    value: 800,
  },
  {
    id: 69,
    name: 'Çamaşır Makinesi',
    emoji: '🚿',
    description: 'Giysi temizler.',
    value: 700,
  },
  {
    id: 70,
    name: 'Bulaşık Makinesi',
    emoji: '🍽️',
    description: 'Tabak yıkar.',
    value: 650,
  },
  {
    id: 71,
    name: 'Drone',
    emoji: '🤖',
    description: 'Otonom uçuş cihazı.',
    value: 900,
  },
  {
    id: 72,
    name: 'Uydu',
    emoji: '🛰️',
    description: 'İletişim ve gözlem uydusu.',
    value: 1500,
  },
  {
    id: 73,
    name: 'Sanal Gerçeklik Gözlüğü',
    emoji: '🎮',
    description: 'Derinlemesine sanal gerçeklik deneyimi.',
    value: 1200,
  },
  {
    id: 74,
    name: 'Akıllı Saat',
    emoji: '⌚',
    description: 'Aktivite ve bildirim takibi.',
    value: 350,
  },
  {
    id: 75,
    name: 'Elektrikli Scooter',
    emoji: '🛴',
    description: 'Çevre dostu kişisel ulaşım aracı.',
    value: 700,
  },
  {
    id: 76,
    name: 'Mikrodalga Fırın',
    emoji: '🎛️',
    description: 'Hızlı ısıtma aracı.',
    value: 450,
  },
  {
    id: 77,
    name: 'Tost Makinesi',
    emoji: '🥪',
    description: 'Lezzetli tostlar yapar.',
    value: 180,
  },
  {
    id: 78,
    name: 'Kahve Makinesi',
    emoji: '☕',
    description: 'Taze kahve demler.',
    value: 350,
  },
  {
    id: 79,
    name: 'Çay Makinesi',
    emoji: '🫖',
    description: 'Sıcak çay demler.',
    value: 280,
  },
  {
    id: 80,
    name: 'Blender',
    emoji: '🥤',
    description: 'Meyve ve sebzeleri püre yapar.',
    value: 220,
  },
  {
    id: 81,
    name: 'Mikser',
    emoji: '🥣',
    description: 'Hamur karıştırıcı.',
    value: 170,
  },
  {
    id: 82,
    name: 'Tava',
    emoji: '🍳',
    description: 'Yemek pişirme tavası.',
    value: 90,
  },
  {
    id: 83,
    name: 'Tencere',
    emoji: '🍲',
    description: 'Çorba ve sulu yemekler için.',
    value: 110,
  },
  {
    id: 84,
    name: 'Çatal',
    emoji: '🍴',
    description: 'Yemek yemek için.',
    value: 10,
  },
  {
    id: 85,
    name: 'Bıçak',
    emoji: '🔪',
    description: 'Keskin mutfak bıçağı.',
    value: 25,
  },
  {
    id: 86,
    name: 'Kaşık',
    emoji: '🥄',
    description: 'Çorba içmek için.',
    value: 10,
  },
  {
    id: 87,
    name: 'Tabak',
    emoji: '🍽️',
    description: 'Yemek sunumu için.',
    value: 15,
  },
  {
    id: 88,
    name: 'Bardak',
    emoji: '🥛',
    description: 'İçecek bardağı.',
    value: 12,
  },
  {
    id: 89,
    name: 'Çaydanlık',
    emoji: '🫖',
    description: 'Geleneksel çay demleme.',
    value: 85,
  },
  {
    id: 90,
    name: 'Kettle',
    emoji: '🫖',
    description: 'Su ısıtıcı.',
    value: 130,
  },
  {
    id: 91,
    name: 'Süpürge',
    emoji: '🧹',
    description: 'Temizlik yapmak için.',
    value: 40,
  },
  {
    id: 92,
    name: 'Vileda',
    emoji: '🧹',
    description: 'Zemin temizliği için.',
    value: 60,
  },
  {
    id: 93,
    name: 'Çöp Kutusu',
    emoji: '🗑️',
    description: 'Atıklar için.',
    value: 35,
  },
  {
    id: 94,
    name: 'Ütü',
    emoji: '🔌',
    description: 'Kırışıklıkları giderir.',
    value: 240,
  },
  {
    id: 95,
    name: 'Ütü Masası',
    emoji: '🪵',
    description: 'Ütü yapmak için zemin.',
    value: 150,
  },
  {
    id: 96,
    name: 'Fön Makinesi',
    emoji: '💨',
    description: 'Saç kurutma aracı.',
    value: 180,
  },
  {
    id: 97,
    name: 'Tarak',
    emoji: '🪮',
    description: 'Saçları düzeltmek için.',
    value: 20,
  },
  {
    id: 98,
    name: 'Ayna',
    emoji: '🪞',
    description: 'Kendinizi görmenizi sağlar.',
    value: 140,
  },
  {
    id: 99,
    name: 'Diş Fırçası',
    emoji: '🪥',
    description: 'Ağız bakımı için.',
    value: 15,
  },
  {
    id: 100,
    name: 'Diş Macunu',
    emoji: '🧴',
    description: 'Dişleri temizler.',
    value: 25,
  },
  {
    id: 101,
    name: 'Şampuan',
    emoji: '🧴',
    description: 'Saç temizliği için.',
    value: 45,
  },
  {
    id: 102,
    name: 'Sabun',
    emoji: '🧼',
    description: 'Genel temizlik sabunu.',
    value: 10,
  },
  {
    id: 103,
    name: 'Havlu',
    emoji: '🧣',
    description: 'Kurulanmak için.',
    value: 50,
  },
  {
    id: 104,
    name: 'Banyo Lif',
    emoji: '🧼',
    description: 'Vücut temizliği için.',
    value: 15,
  },
  {
    id: 105,
    name: 'Tuvalet Kağıdı',
    emoji: '🧻',
    description: 'Kişisel hijyen.',
    value: 30,
  },
  {
    id: 106,
    name: 'Parfüm',
    emoji: '🧴',
    description: 'Güzel koku verir.',
    value: 300,
  },
  {
    id: 107,
    name: 'Deodorant',
    emoji: '🧴',
    description: 'Kötü kokuları önler.',
    value: 75,
  },
  {
    id: 108,
    name: 'Krem',
    emoji: '🧴',
    description: 'Cildi nemlendirir.',
    value: 90,
  },
  {
    id: 109,
    name: 'Ruj',
    emoji: '💄',
    description: 'Dudak boyası.',
    value: 120,
  },
  {
    id: 110,
    name: 'Maskara',
    emoji: '👁️',
    description: 'Kirpikleri belirginleştirir.',
    value: 140,
  },
  {
    id: 111,
    name: 'Oje',
    emoji: '💅',
    description: 'Tırnak boyası.',
    value: 30,
  },
  {
    id: 112,
    name: 'Göz Farı',
    emoji: '🎨',
    description: 'Göz makyajı paleti.',
    value: 160,
  },
  {
    id: 113,
    name: 'Allık',
    emoji: '🧴',
    description: 'Yanakları renklendirir.',
    value: 110,
  },
  {
    id: 114,
    name: 'Tırnak Makası',
    emoji: '✂️',
    description: 'Tırnak kesmek için.',
    value: 40,
  },
  {
    id: 115,
    name: 'Cımbız',
    emoji: '✂️',
    description: 'Kişisel bakım aracı.',
    value: 25,
  },
  {
    id: 116,
    name: 'Pamuk',
    emoji: '☁️',
    description: 'Temizlik pamuğu.',
    value: 15,
  },
  {
    id: 117,
    name: 'Aspirin',
    emoji: '💊',
    description: 'Ağrı kesici.',
    value: 50,
  },
  {
    id: 118,
    name: 'Vitamin',
    emoji: '💊',
    description: 'Gıda takviyesi.',
    value: 120,
  },
  {
    id: 119,
    name: 'Bandaj',
    emoji: '🩹',
    description: 'Yara sarmak için.',
    value: 30,
  },
  {
    id: 120,
    name: 'Yara Bandı',
    emoji: '🩹',
    description: 'Küçük yaralar için.',
    value: 10,
  },
  {
    id: 121,
    name: 'Termometre',
    emoji: '🌡️',
    description: 'Vücut ısısını ölçer.',
    value: 80,
  },
  {
    id: 122,
    name: 'Oksijenli Su',
    emoji: '🧪',
    description: 'Dezenfektan sıvı.',
    value: 40,
  },
  {
    id: 123,
    name: 'Maske',
    emoji: '😷',
    description: 'Yüz koruyucu maske.',
    value: 15,
  },
  {
    id: 124,
    name: 'Eldiven',
    emoji: '🧤',
    description: 'El koruyucu.',
    value: 20,
  },
  {
    id: 125,
    name: 'Göz Damlası',
    emoji: '💧',
    description: 'Göz kuruluğu için.',
    value: 65,
  },
  {
    id: 126,
    name: 'Öksürük Şurubu',
    emoji: '🧪',
    description: 'Boğazı rahatlatır.',
    value: 95,
  },
  {
    id: 127,
    name: 'Sargı Bezi',
    emoji: '🩹',
    description: 'Yaraları korumak için.',
    value: 25,
  },
  {
    id: 128,
    name: 'Yüzük',
    emoji: '💍',
    description: 'Değerli bir takı.',
    value: 1000,
  },
  {
    id: 129,
    name: 'Kolye',
    emoji: '📿',
    description: 'Şık boyun takısı.',
    value: 850,
  },
  {
    id: 130,
    name: 'Küpe',
    emoji: '💎',
    description: 'Kulak aksesuarı.',
    value: 600,
  },
  {
    id: 131,
    name: 'Bilezik',
    emoji: '🪙',
    description: 'Altın kol takısı.',
    value: 1200,
  },
  {
    id: 132,
    name: 'Taç',
    emoji: '👑',
    description: 'Kraliyet simgesi.',
    value: 5000,
  },
  {
    id: 133,
    name: 'Gerdanlık',
    emoji: '💍',
    description: 'Elmas gerdanlık.',
    value: 4500,
  },
  {
    id: 134,
    name: 'Broş',
    emoji: '🎗️',
    description: 'Kıyafet aksesuarı.',
    value: 350,
  },
  {
    id: 135,
    name: 'Kravat',
    emoji: '👔',
    description: 'Resmi giyim aksesuarı.',
    value: 110,
  },
  {
    id: 136,
    name: 'Kemer',
    emoji: '👖',
    description: 'Pantolon kemeri.',
    value: 95,
  },
  {
    id: 137,
    name: 'Şapka',
    emoji: '🧢',
    description: 'Güneşten korur.',
    value: 80,
  },
  {
    id: 138,
    name: 'Bere',
    emoji: '🧣',
    description: 'Soğuktan korur.',
    value: 60,
  },
  {
    id: 139,
    name: 'Atkı',
    emoji: '🧣',
    description: 'Boynu sıcak tutar.',
    value: 70,
  },
  {
    id: 140,
    name: 'Eldiven (Kışlık)',
    emoji: '🧤',
    description: 'Elleri sıcak tutar.',
    value: 55,
  },
  {
    id: 141,
    name: 'Çorap',
    emoji: '🧦',
    description: 'Ayak giysisi.',
    value: 25,
  },
  {
    id: 142,
    name: 'Ayakkabı',
    emoji: '👟',
    description: 'Günlük yürüyüş ayakkabısı.',
    value: 400,
  },
  {
    id: 143,
    name: 'Bot',
    emoji: '🥾',
    description: 'Kışlık dayanıklı bot.',
    value: 650,
  },
  {
    id: 144,
    name: 'Terlik',
    emoji: '🩴',
    description: 'Ev terliği.',
    value: 80,
  },
  {
    id: 145,
    name: 'Ceket',
    emoji: '🧥',
    description: 'Şık dış giyim ceket.',
    value: 500,
  },
  {
    id: 146,
    name: 'Palto',
    emoji: '🧥',
    description: 'Kışlık sıcak palto.',
    value: 850,
  },
  {
    id: 147,
    name: 'Pantolon',
    emoji: '👖',
    description: 'Klasik pantolon.',
    value: 300,
  },
  {
    id: 148,
    name: 'Gömlek',
    emoji: '👔',
    description: 'Üst giyim gömlek.',
    value: 250,
  },
  {
    id: 149,
    name: 'T-Shirt',
    emoji: '👕',
    description: 'Rahat t-shirt.',
    value: 150,
  },
  {
    id: 150,
    name: 'Sweatshirt',
    emoji: '👕',
    description: 'Kapüşonlu sweatshirt.',
    value: 280,
  },
  {
    id: 151,
    name: 'Hırka',
    emoji: '🧥',
    description: 'Örme hırka.',
    value: 220,
  },
  {
    id: 152,
    name: 'Yelek',
    emoji: '🦺',
    description: 'Ekstra sıcaklık sağlar.',
    value: 180,
  },
  {
    id: 153,
    name: 'Elbise',
    emoji: '👗',
    description: 'Kadın elbisesi.',
    value: 600,
  },
  {
    id: 154,
    name: 'Etek',
    emoji: '👗',
    description: 'Şık etek.',
    value: 250,
  },
  {
    id: 155,
    name: 'Pijama',
    emoji: '👕',
    description: 'Gece uykusu giysisi.',
    value: 200,
  },
  {
    id: 156,
    name: 'Bornoz',
    emoji: '🥋',
    description: 'Banyo sonrası bornoz.',
    value: 350,
  },
  {
    id: 157,
    name: 'Mayo',
    emoji: '🩱',
    description: 'Deniz kıyafeti.',
    value: 180,
  },
  {
    id: 158,
    name: 'Şort',
    emoji: '🩳',
    description: 'Yazlık şort.',
    value: 130,
  },
  {
    id: 159,
    name: 'Valiz',
    emoji: '🧳',
    description: 'Seyahat çantası.',
    value: 450,
  },
  {
    id: 160,
    name: 'Sırt Çantası',
    emoji: '🎒',
    description: 'Okul ve kamp çantası.',
    value: 250,
  },
  {
    id: 161,
    name: 'El Çantası',
    emoji: '👜',
    description: 'Kişisel çanta.',
    value: 350,
  },
  {
    id: 162,
    name: 'Cüzdan',
    emoji: '🪙',
    description: 'Para ve kartlar için.',
    value: 150,
  },
  {
    id: 163,
    name: 'Gitar',
    emoji: '🎸',
    description: 'Müzik aleti.',
    value: 800,
  },
  {
    id: 164,
    name: 'Piyano',
    emoji: '🎹',
    description: 'Tuşlu enstrüman.',
    value: 3500,
  },
  {
    id: 165,
    name: 'Keman',
    emoji: '🎻',
    description: 'Yaylı çalgı.',
    value: 1200,
  },
  {
    id: 166,
    name: 'Flüt',
    emoji: '🎵',
    description: 'Üflemeli çalgı.',
    value: 150,
  },
  {
    id: 167,
    name: 'Davul',
    emoji: '🥁',
    description: 'Vurmalı çalgı.',
    value: 1800,
  },
  {
    id: 168,
    name: 'Saz',
    emoji: '🪕',
    description: 'Geleneksel Türk çalgısı.',
    value: 600,
  },
  {
    id: 169,
    name: 'Mikrofon Standı',
    emoji: '🎙️',
    description: 'Mikrofon tutucu.',
    value: 180,
  },
  {
    id: 170,
    name: 'Kulaklık Amfisi',
    emoji: '🔌',
    description: 'Ses güçlendirici.',
    value: 400,
  },
  {
    id: 171,
    name: 'Futbol Topu',
    emoji: '⚽',
    description: 'Maç topu.',
    value: 150,
  },
  {
    id: 172,
    name: 'Basketbol Topu',
    emoji: '🏀',
    description: 'Basketbol için.',
    value: 180,
  },
  {
    id: 173,
    name: 'Tenis Raketi',
    emoji: '🎾',
    description: 'Tenis oynamak için.',
    value: 320,
  },
  {
    id: 174,
    name: 'Masa Tenisi Raketi',
    emoji: '🏓',
    description: 'Küçük raket.',
    value: 90,
  },
  {
    id: 175,
    name: 'Badminton Raketi',
    emoji: '🏸',
    description: 'Badminton için.',
    value: 120,
  },
  {
    id: 176,
    name: 'Kaykay',
    emoji: '🛹',
    description: 'Sokak sporu için.',
    value: 250,
  },
  {
    id: 177,
    name: 'Bisiklet',
    emoji: '🚲',
    description: 'İki tekerlekli ulaşım.',
    value: 1800,
  },
  {
    id: 178,
    name: 'Kask',
    emoji: '🪖',
    description: 'Güvenlik kaskı.',
    value: 220,
  },
  {
    id: 179,
    name: 'Paten',
    emoji: '🛼',
    description: 'Tekerlekli paten.',
    value: 350,
  },
  {
    id: 180,
    name: 'Koşu Bandı',
    emoji: '🏃',
    description: 'Evde spor için.',
    value: 2500,
  },
  {
    id: 181,
    name: 'Dambıl',
    emoji: '🏋️',
    description: 'Ağırlık antrenmanı.',
    value: 140,
  },
  {
    id: 182,
    name: 'Mat (Spor)',
    emoji: '🧘',
    description: 'Yoga ve egzersiz matı.',
    value: 100,
  },
  {
    id: 183,
    name: 'Kamp Çadırı',
    emoji: '⛺',
    description: 'Dış mekan barınağı.',
    value: 800,
  },
  {
    id: 184,
    name: 'Uyku Tulumu',
    emoji: '⛺',
    description: 'Kampta sıcak tutar.',
    value: 350,
  },
  {
    id: 185,
    name: 'Kamp Sandalyesi',
    emoji: '🪑',
    description: 'Katlanabilir sandalye.',
    value: 200,
  },
  {
    id: 186,
    name: 'Termos',
    emoji: '🥛',
    description: 'İçecekleri sıcak/soğuk tutar.',
    value: 180,
  },
  {
    id: 187,
    name: 'Olta',
    emoji: '🎣',
    description: 'Balık tutmak için.',
    value: 400,
  },
  {
    id: 188,
    name: 'Çakı',
    emoji: '🔪',
    description: 'Çok amaçlı kamp bıçağı.',
    value: 150,
  },
  {
    id: 189,
    name: 'Çakmak',
    emoji: '🔥',
    description: 'Ateş yakıcı.',
    value: 15,
  },
  {
    id: 190,
    name: 'Kibrit',
    emoji: '🧣',
    description: 'Klasik ateş yakıcı.',
    value: 5,
  },
  {
    id: 191,
    name: 'Hamak',
    emoji: '🕸️',
    description: 'Ağaç arası yatak.',
    value: 180,
  },
  {
    id: 192,
    name: 'Dürbün',
    emoji: '🔭',
    description: 'Uzakları izlemek için.',
    value: 350,
  },
  {
    id: 193,
    name: 'Fener (Kamp)',
    emoji: '🏮',
    description: 'Geniş açılı kamp feneri.',
    value: 120,
  },
  {
    id: 194,
    name: 'Mangal',
    emoji: '🍢',
    description: 'Piknik ve barbekü.',
    value: 450,
  },
  {
    id: 195,
    name: 'Kömür',
    emoji: '🪨',
    description: 'Mangal yakıtı.',
    value: 80,
  },
  {
    id: 196,
    name: 'Tuz',
    emoji: '🧂',
    description: 'Lezzet verici mineral.',
    value: 10,
  },
  {
    id: 197,
    name: 'Karabiber',
    emoji: '🌶️',
    description: 'Baharat çeşidi.',
    value: 15,
  },
  {
    id: 198,
    name: 'Zeytinyağı',
    emoji: '🫙',
    description: 'Sağlıklı yemeklik yağ.',
    value: 180,
  },
  {
    id: 199,
    name: 'Salça',
    emoji: '🥫',
    description: 'Yemeklik domates salçası.',
    value: 45,
  },
  {
    id: 200,
    name: 'Makarna',
    emoji: '🍝',
    description: 'Kolay pişen hamur işi.',
    value: 20,
  },
  {
    id: 201,
    name: 'Pirinç',
    emoji: '🌾',
    description: 'Pilav yapımında kullanılır.',
    value: 40,
  },
  {
    id: 202,
    name: 'Bulgur',
    emoji: '🌾',
    description: 'Geleneksel Anadolu tahılı.',
    value: 30,
  },
  {
    id: 203,
    name: 'Un',
    emoji: '🥣',
    description: 'Hamur işlerinin temel maddesi.',
    value: 35,
  },
  {
    id: 204,
    name: 'Şeker',
    emoji: '🍬',
    description: 'Tatlandırıcı kristaller.',
    value: 50,
  },
  {
    id: 205,
    name: 'Çay (Kuru)',
    emoji: '🍃',
    description: 'Demlemek için kuru çay yaprağı.',
    value: 90,
  },
  {
    id: 206,
    name: 'Türk Kahvesi',
    emoji: '☕',
    description: 'Geleneksel Türk kahvesi.',
    value: 65,
  },
  {
    id: 207,
    name: 'Maya',
    emoji: '🍞',
    description: 'Hamur kabartıcı.',
    value: 15,
  },
  {
    id: 208,
    name: 'Sıvı Yağ',
    emoji: '🫙',
    description: 'Yemeklik bitkisel yağ.',
    value: 110,
  },
  {
    id: 209,
    name: 'Sirke',
    emoji: '🫙',
    description: 'Salata ve turşu için.',
    value: 30,
  },
  {
    id: 210,
    name: 'Limon',
    emoji: '🍋',
    description: 'Ekşi narenciye meyvesi.',
    value: 15,
  },
];

module.exports = items;
